-- Historical marker migration — issue #22 (Phase 4.5 Lane A2), "migration
-- history alignment." See 20260524154102_init_bossa_ai_os_core.sql's header
-- comment for the full rationale — this file exists only to match remote's
-- already-tracked history for `bossa-ai-os`, never to encode real DDL/DML.
--
-- This is the version whose name indicates `private.is_bossa_operator` was
-- moved into a non-exposed `private` schema on the legacy project — this
-- repository never creates or references a `private` schema itself, so
-- there is no collision here. See
-- docs/PRODUCTION_SCHEMA_COLLISION_CLEANUP_PLAN.md's "Legacy functions"
-- table.
--
-- Deliberately a no-op: zero DDL, zero DML.
